KEYWORD_MAP = {
    "jadwal_kuliah": ["jadwal kuliah", "jadwal kelas", "jadwal perkuliahan", "jam kuliah"],
    "biaya": ["biaya", "ukt", "biaya kuliah", "biaya persemester", "berapa biaya"],
    "fasilitas": ["fasilitas", "lab", "wifi", "perpustakaan", "ruang belajar", "mushola"],
    "alamat": ["alamat", "lokasi", "dimana kampus", "letak kampus"],
    "program_studi": ["prodi", "jurusan", "program studi", "daftar jurusan"],
    "kontak": ["kontak", "nomor", "email", "hubungi", "admin"],
    "pendaftaran": ["pendaftaran", "daftar", "registrasi", "pmb"],
    "beasiswa": ["beasiswa", "kip", "kip kuliah"],
    "organisasi": ["organisasi", "ukm", "bem", "rohis", "kmk"],
    "dosen": ["dosen", "pengajar", "tenaga pengajar"],
    "krs": ["krs", "isi krs", "kartu rencana studi"],
    "khs": ["khs", "nilai", "hasil studi", "lihat nilai"],
    "bayar_ukt": ["bayar ukt", "pembayaran", "transfer", "briva"],
    "login_issue": ["gagal login", "tidak bisa login", "error login", "ga bisa login", "gabisa login"],
    "reset_password": ["lupa password", "reset password", "ganti password", "lupa pw"],
    "gagal_daftar": ["gagal daftar", "gagal mendaftar", "error pendaftaran", "tidak bisa daftar"],
    "lupa_data_login": ["lupa nim", "lupa email", "lupa data login", "lupa akun"],
    "siakad_error": ["siakad error", "error siakad", "server down", "siakad tidak bisa dibuka"],
    "terimakasih": ["terima kasih", "makasih", "thanks", "sudah benar", "oke", "ok", "siap", "bisa", "berhasil"],
    "penusa_bot": ["penusa bot", "kamu siapa", "bot ini apa", "kau ni ape", "anda siapa"],
    "ti": ["teknik informatika", "ti itu apa", "coding", "programmer"],
    "teknologi_informasi": ["teknologi informasi", "jurusan ti", "jaringan", "network", "server"],
    "bisnis_digital": ["bisnis digital", "jurusan bisnis", "e-commerce", "digital marketing", "startup"],
    "stimik": ["stimik", "stmik", "kepanjangan stimik", "apa itu stimik"],
    "lihat_data_mahasiswa": ["lihat data mahasiswa", "profil mahasiswa", "biodata", "data diri", "profil saya"],
    "akses_siakad": ["akses siakad", "cara login siakad", "masuk siakad", "login siakad", "edlink"],
    "kalender_akademik": ["kalender akademik", "jadwal akademik", "tanggal penting", "jadwal uts", "jadwal uas"],
    "lihat_ruang_kelas": ["ruang kelas", "lihat ruang", "monitor kampus", "ruang kuliah"],
    "website_kampus": ["website kampus", "pmb.pelitanusantara", "situs kampus", "web kampus"],
    "pujian_bot": ["bot keren", "kamu keren", "pintar bot", "keren bot"],
    "hinaan_kritik": ["goblok", "bodoh", "tolol", "bego", "jelek bot"]
}